x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      - Update base image
      - Make zone.name a mandatory field
  images:
    '':
      properties:
        agent.image.name:
          type: FULL
    leader-elector:
      properties:
        leaderElector.image.name:
          type: FULL

  clusterConstraints:
    resources:
    - replicas: 1
      requests:
        cpu: 500m
        memory: 512Mi

required:
  - agent.endpointHost
  - agent.key
  - agent.endpointPort
  - name
  - namespace
  - zone.name

properties:
  agent.key:
    type: string
    title: Instana Agent Key
    description: "Your Instana Agent key is the secret token which your agent uses to authenticate to Instana's servers"
  zone.name:
    type: string
    title: Instana Zone Name
    description: Custom zone that detected technologies will be assigned to
  name:
    type: string
    default: "$APP_NAME"
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    default: "$APP_NAME"
    x-google-marketplace:
      type: NAMESPACE
  agent.downloadKey:
    type: string
    title: Instana Download Key (Optional)
  agent.endpointHost:
    type: string
    title: Instana Agent backend endpoint host
    default: ingress-red-saas.instana.io
  agent.endpointPort:
    type: string
    title: Instana Agent backend endpoint port
    default: "443"
  agent.tls.secretName:
    type: string
    title: Name of the secret of type kubernetes.io/tls (Optional)
    description: "In order to enable TLS, a secret of type kubernetes.io/tls must be specified."
  agent.leaderElectorPort:
    type: integer
    title: Instana leader elector sidecar port
    default: 42655
  agent.listenAddress:
    type: string
    title: List of addresses to listen on (Optional)
    description: List of addresses to listen on, or "*" for all interfaces
  agent.pod.limits.cpu:
    type: string
    title: Container CPU limits in CPU cores
    default: "1.5"
  agent.pod.limits.memory:
    type: integer
    title: Container memory limits in MiB
    default: 768
  agent.pod.proxyHost:
    type: string
    title: Hostname/address of a proxy (Optional)
    description: Sets the INSTANA_AGENT_PROXY_HOST environment variable
  agent.pod.proxyPort:
    type: string
    title: Port of a proxy (Optional)
    description: Sets the INSTANA_AGENT_PROXY_PORT environment variable
  agent.pod.proxyProtocol:
    type: string
    title: Proxy protocol (Optional)
    description: Sets the INSTANA_AGENT_PROXY_PROTOCOL environment variable. Supported proxy types are http, socks4, socks5
    enum:
      - "http"
      - "socks4"
      - "socks5"
  agent.pod.proxyUser:
    type: string
    title: Username of the proxy auth (Optional)
    description: Sets the INSTANA_AGENT_PROXY_USER environment variable
  agent.pod.proxyPassword:
    type: string
    title: Password of the proxy auth (Optional)
    description: Sets the INSTANA_AGENT_PROXY_PASSWORD environment variable
  agent.pod.proxyUserDNS:
    type: boolean
    title: Boolean if proxy also does DNS (Optional)
    description: Sets the INSTANA_AGENT_PROXY_USE_DNS environment variable
  agent.pod.requests.cpu:
    type: string
    title: Container CPU requests in CPU cores
    default: "0.5"
  agent.pod.requests.memory:
    type: integer
    title: Container memory requests in MiB
    default: 512
  agent.redactKubernetesSecrets:
    type: boolean
    title: Enable additional secrets redaction for selected Kubernetes resources
    description: See https://docs.instana.io/quick_start/agent_setup/container/kubernetes/#secrets for more details
    default: false
  cluster.name:
    type: string
    title: Display name of the monitored cluster (Optional)
    description: The optional name that will be assigned to this cluster in Instana. See https://github.com/helm/charts/tree/master/stable/instana-agent#installing-the-chart for more details
  agent.serviceAccount:
    type: string
    title: Cluster Admin Service Account
    description: >-
      Name of a service account in the target namespace.
      These permissions are needed for the Instana Agent
      to monitor Kubernetes infrastructure
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: Service account used by Instana Agent
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: ["batch"]
                resources:
                  - "jobs"
                  - "cronjobs"
                verbs: ["get", "list", "watch"]
              - apiGroups: ["extensions"]
                resources:
                  - "deployments"
                  - "replicasets"
                  - "ingresses"
                verbs: ["get", "list", "watch"]
              - apiGroups: ["apps"]
                resources:
                  - "deployments"
                  - "replicasets"
                  - "daemonsets"
                  - "statefulsets"
                verbs: ["get", "list", "watch"]
              - apiGroups: [""]
                resources:
                  - "namespaces"
                  - "events"
                  - "services"
                  - "endpoints"
                  - "nodes"
                  - "pods"
                  - "replicationcontrollers"
                  - "componentstatuses"
                  - "resourcequotas"
                  - "persistentvolumes"
                  - "persistentvolumeclaims"
                verbs: ["get", "list", "watch"]
              - apiGroups: [""]
                resources:
                  - "endpoints"
                verbs: ["create", "update", "patch"]
              - apiGroups: ["networking.k8s.io"]
                resources:
                  - "ingresses"
                verbs: ["get", "list", "watch"]
