applicationApiVersion: v1beta1

properties:
  agent.endpointHost:
    type: string
    title: Instana Service Endpoint
    default: saas-us-west-2.instana.io
  agent.endpointPort:
    type: string
    title: Instana Service Port
    default: "443"
  agent.image.name:
    type: string
    default: $REGISTRY/$APP_NAME:$TAG
    x-google-marketplace:
      type: IMAGE
  agent.key:
    type: string
    title: Instana Agent Key
    description: Instana Agent key, acquire this key from Instana service
  computeResources.limits.cpu:
    type: string
    title: Container cpu limits in cpu cores
    default: "1.5"
  computeResources.limits.memory:
    type: integer
    title: Container memory limits in MiB
    default: 512
  computeResources.requests.cpu:
    type: string
    title: Container cpu requests in cpu cores
    default: "0.5"
  computeResources.requests.memory:
    type: integer
    title: Container memory requests in MiB
    default: 512
  name:
    type: string
    default: instana-agent
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    default: instana-agent
    x-google-marketplace:
      type: NAMESPACE
  serviceAccount:
    type: string
    title: Instana Agent Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - nonResourceURLs:
              - "/version"
              - "/healthz"
            verbs: ["get"]
          - apiGroups: ["batch"]
            resources:
              - "jobs"
            verbs: ["get", "list", "watch"]
          - apiGroups: ["extensions"]
            resources:
              - "deployments"
              - "replicasets"
              - "ingresses"
            verbs: ["get", "list", "watch"]
          - apiGroups: ["apps"]
            resources:
              - "deployments"
              - "replicasets"
            verbs: ["get", "list", "watch"]
          - apiGroups: [""]
            resources:
              - "namespaces"
              - "events"
              - "services"
              - "endpoints"
              - "nodes"
              - "pods"
              - "replicationcontrollers"
              - "componentstatuses"
              - "resourcequotas"
            verbs: ["get", "list", "watch"]
          - apiGroups: [""]
            resources:
              - "endpoints"
            verbs: ["create", "update", "patch"]
  zone.name:
    type: string
    title: Instana Zone Name
    description: Name of the cluster that will appear on Instana launch map
required:
- agent.endpointHost
- agent.endpointPort
- agent.image.name
- agent.key
- computeResources.limits.cpu
- computeResources.limits.memory
- computeResources.requests.cpu
- computeResources.requests.memory
- name
- namespace
- serviceAccount
- zone.name
x-google-marketplace:
  clusterConstraints:
    resources:
    - replicas: 1
      requests:
        cpu: 500m
        memory: 512Mi
