properties:
  zone.name:
    type: string
    title: Instana Zone Name
    default: kubernetes-cluster
  agent.image.name:
    type: string
    default: $REGISTRY/$APP_NAME:$TAG
    x-google-marketplace:
      type: IMAGE
  agent.key:
    type: string
    title: Instana Agent Key
    description: "Your Instana Agent key is the secret token which your agent uses to authenticate to Instana's servers"
    default: dummyAgentKey
