properties:
  agent.key:
    type: string
    default: dummyAgentKey
  zone.name:
    type: string
    default: "test-zone"
  testerImage:
    type: string
    default: $REGISTRY/$APP_NAME/tester:$DEPLOYER_TAG
    x-google-property:
      type: IMAGE
